### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mirekys** [oarepo/oarepo-communities#3]
- [ ] DB table to hold community to Perun group mappings
- [ ] RecordSearch derived from enrollments to filter with community id from request
- [ ] Permission factories for actions on community (require_any, require_all)
- [ ] one record in a single community only (but in metadata it is a list 'communities': [...])
- [ ] CommunityEnforcing mixin that prevents removal/change of community in metadata
- [ ] Draft rest endpoints that accepts community id, e.g /api/[draft]/<community_id>/<record_id>
